### PR TITLE
'checked' improperly handles truthy values

### LINKED ISSUE #242: Truthy value for 'checked' shows selection, but item is missing from answers
Suppling a truthy value to 'checked' results in the list item being selected visually, but it is missing from the selected elements list.

The following test case fails as the second item is omitted from the answers:

```js
  it("provide an array of checked choice to validate", function( done ) {
    this.fixture.choices = [
      { name: "1", checked: true  },
      { name: "2", checked: 1 },
      { name: "3", checked: false }
    ];
    this.fixture.validate = function( answer ) {
      expect(answer).to.eql([ "1", "2" ]);
      return true;
    };
    this.checkbox = new Checkbox( this.fixture, this.rl );
    this.checkbox.run(function() {
      done();
    });
    this.rl.emit("line");
  });
```

### PR DESCRIPTION
**Pull request by plemarquand**
Suppling a truthy value to 'checked' resulted in the list item
being selected visually, but it was missing from the selected
elements list.

'checked' is now coerced to a boolean when selected items are
queried.

This patch closes #242.

### CODE REVIEW

File: test/specs/prompts/checkbox.js [hunk 1]
```diff
@@ -85,6 +85,8 @@ describe("`checkbox` prompt", function() {
     this.rl.emit("line");
   });
 
+
```
Comment (SBoudrias) [inline test/specs/prompts/checkbox.js]: can you remove the extra whitespace

Comment (plemarquand) [inline test/specs/prompts/checkbox.js]: @SBoudrias Done

**Comment by SBoudrias** [comment]
Thanks!
